### ISSUE TITLE
System.Net.Http.CurlExeption :Peer certificate cannot be authenticated with given CA certificate

### ISSUE THREAD

**Issue by gsainagendraprasad** [SteeltoeOSS/Workshop#3]
Hi , I logged in to pcf dev using cf login -a https://api.local.pcfdev.io --skip-ssl-validation  and published both my client and service applications. when i call the client url , i am getting HTTP 500 error, when i saw the logs it says -

2017-04-28T17:26:01.50-0500 [APP/PROC/WEB/0] OUT fail: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
2017-04-28T17:26:01.50-0500 [APP/PROC/WEB/0] OUT       DoGetApplicationsAsync Exception: System.Net.Http.HttpRequestExce
ption: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authe
nticated with given CA certificates

please help me on this error:

As I was reading through : http://steeltoe.io/docs/steeltoe-discovery/#1-2-2-1-settings-to-discover
this they are saying i may run into ssl certificate issues, is this error related with this ??

**Comment by dtillman** [comment]
Closing as question was posted and answered in another repo.
